export const GET_HOME_INFO = 'GET_HOME_INFO'
export const GET_HOME_INFO_SUCCESS = 'GET_HOME_INFO_SUCCESS'
export const GET_HOME_INFO_FAIL = 'GET_HOME_INFO_FAIL'

export const RESET_STATE = 'RESET_STATE'
