export const SET_LIST_PRODUCT = 'SET_LIST_PRODUCT'

export const CHECKOUT = 'CHECKOUT'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL'

export const SET_USER_FORM = 'SET_USER_FORM'

export const SET_IMAGE_BASE64 = 'SET_IMAGE_BASE64'

export const SET_ADVANCE_PRODUCT = 'SET_ADVANCE_PRODUCT'
