export const GET_LIST_STYLE = 'GET_LIST_STYLE'
export const GET_LIST_STYLE_SUCCESS = 'GET_LIST_STYLE_SUCCESS'
export const GET_LIST_STYLE_FAIL = 'GET_LIST_STYLE_FAIL'

export const GET_LIST_ROOM_SIZE = 'GET_LIST_ROOM_SIZE'
export const GET_LIST_ROOM_SIZE_SUCCESS = 'GET_LIST_ROOM_SIZE_SUCCESS'
export const GET_LIST_ROOM_SIZE_FAIL = 'GET_LIST_ROOM_SIZE_FAIL'

export const GET_LIST_ROOM_KIND = 'GET_LIST_ROOM_KIND'
export const GET_LIST_ROOM_KIND_SUCCESS = 'GET_LIST_ROOM_KIND_SUCCESS'
export const GET_LIST_ROOM_KIND_FAIL = 'GET_LIST_ROOM_KIND_FAIL'

export const GET_STYLE_PRODUCTS = 'GET_STYLE_PRODUCTS'
export const GET_STYLE_PRODUCTS_SUCCESS = 'GET_STYLE_PRODUCTS_SUCCESS'
export const GET_STYLE_PRODUCTS_FAIL = 'GET_STYLE_PRODUCTS_FAIL'

export const GET_LIST_BUILDING_TYPE = 'GET_LIST_BUILDING_TYPE'
export const GET_LIST_BUILDING_TYPE_SUCCESS = 'GET_LIST_BUILDING_TYPE_SUCCESS'
export const GET_LIST_BUILDING_TYPE_FAIL = 'GET_LIST_BUILDING_TYPE_FAIL'

export const SET_ADVANCE_STYLE = 'SET_ADVANCE_STYLE'
